Added Read me
yassine-mdn/attch-reminder pull request #6
Opened 2024-12-09 13:17 UTC by Abhishek022001

ReadMe file has been added

2024-12-09 15:02 UTC, yassine-mdn requested changes
the README.md doesn't match the app

2024-12-09 15:02 UTC, yassine-mdn commented on README.md
> +   python main.py
its a chrome extension, not a python app

2024-12-10 13:11 UTC, Abhishek022001 commented
Pls check now

2024-12-10 13:41 UTC, yassine-mdn approved these changes

2024-12-10 13:41 UTC, merged

2024-12-14 18:54 UTC, yassine-mdn commented
close #1